version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  linting_testing:
    docker:
      - image: python:3.8.16-alpine3.18
    steps:
      - checkout     
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest 




workflows:
  deployment_process:
    jobs:
      - linting_testing