version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  pass_test:
    docker:
      - image: cimg/python:3.8.16

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest
            flake8

  build_image:
    docker:
      - image: cimg/python:3.8.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt      
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            TAG=$CIRCLE_SHA1 
            docker build -t rhunold/amd64_image_oc_letting:$TAG .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push rhunold/amd64_image_oc_letting:$TAG

          # echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin            

  deploy_heroku:
    # machine: true  
    executor: heroku/default
    # docker:
    #   - image: cimg/python:3.8.16
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true      
      - run:
          name: Deploy Docker image to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push --app oc-letting web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release --app oc-letting web

workflows:
  version: 2
  deployment_process:
    jobs:
      - pass_test
      - build_image:      
          requires:
            - pass_test
          filters:
            branches:
              only:
                - master
      - deploy_heroku:      
          requires:
            - build_image
          filters:
            branches:
              only:
                - master                
    public: true