version: 2.1

# orbs:
#   python: circleci/python@2.0.3
#   heroku: circleci/heroku@1.2.6



jobs:
  linting_testing:
    docker:
      - image: python:3.8.16-slim-bullseye
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt      
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest 

  docker_hub:
    docker:
      - image: $DOCKERHUB_USERNAME/image_oc_letting:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      # - setup_remote_docker:
      #     version: 20.10.18
      #     docker_layer_caching: true

      # - run: 
      #     name: get the id of the last commit
      #     command: COMMIT_HASH=$(git rev-parse HEAD)    
      # - run: 
      #     name: login with docker
      #     command: |
      #       echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      # - run: 
      #     name: build docker image with Dockerfile and add CircleCI tag hash
      #     command: docker build -t $DOCKERHUB_USERNAME/image_oc_letting:$COMMIT_HASH .
      # - run: 
      #     name: push docker image to dockerhub
      #     command: docker push $DOCKERHUB_USERNAME/image_oc_letting:$COMMIT_HASH

      - run: 
          name: push docker image to dockerhub
          command: |
            COMMIT_HASH=$(git rev-parse HEAD)
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build . -t $DOCKERHUB_USERNAME/image_oc_letting:$COMMIT_HASH
            docker tag $DOCKERHUB_USERNAME/image_oc_letting:$COMMIT_HASH $DOCKERHUB_USERNAME/image_oc_letting:latest
            docker push $DOCKERHUB_USERNAME/image_oc_letting:$COMMIT_HASH
            docker push $DOCKERHUB_USERNAME/image_oc_letting:latest


workflows:
  deployment_process:
    jobs:
      - linting_testing
      - docker_hub:      
          requires:
            - linting_testing # only push to docker is tests are ok         