version: 2.1

orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@1.2.6



jobs:
  linting_testing:
    docker:
      - image: rhunold/amd64_image_oc_letting:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt      
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest 

  docker_hub:
    docker:
      - image: rhunold/amd64_image_oc_letting:latest
        # auth:
        #   username: $DOCKERHUB_USERNAME
        #   password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - setup_remote_docker:
          version: 20.10.11

      - run: 
          name: push docker image to dockerhub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build . -t $DOCKERHUB_USERNAME/amd64_image_oc_letting:$CIRCLE_SHA1
            docker tag $DOCKERHUB_USERNAME/amd64_image_oc_letting:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/amd64_image_oc_letting:latest
            docker push $DOCKERHUB_USERNAME/amd64_image_oc_letting:latest
            docker push $DOCKERHUB_USERNAME/amd64_image_oc_letting:$CIRCLE_SHA1            

          # echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin            

          # $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
          # TAG=$(git rev-parse HEAD)
          # TAG=(git --git-dir=https://github.com/rhunold/projet13 rev-parse HEAD)

workflows:
  deployment_process:
    jobs:
      - linting_testing
      - docker_hub:      
          requires:
            - linting_testing
          filters:
            branches:
              only:
                - master    