# Generated by Django 3.0 on 2023-05-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20230512_1705'),
        ('lettings', '0002_auto_20230512_1706'),
        ('profiles', '0002_auto_20230512_1723'),        
        
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
    ]
