# Generated by Django 3.0 on 2023-05-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20230512_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
